default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST") { "localhost" } %>
  username: <%= Rails.application.credentials.database[:username] %>
  password: <%= Rails.application.credentials.database[:password] %>
  database: <%= Rails.application.credentials.database[:db_name] %>

development:
  <<: *default

test:
  <<: *default
  database: accountsdb_test

production:
  <<: *default